name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN secret is missing or empty."
            exit 1
          fi
          git remote add hf https://tancse2005:$HF_TOKEN@huggingface.co/spaces/tancse2005/Detect-transferring-threat-by-AI-with-Blockchain
          git push hf main --force
